#!/bin/bash

echo "================================================"
echo "Deploying Bvester to bvester.com"
echo "================================================"

echo ""
echo "Step 1: Building and deploying to Firebase..."
firebase deploy --only hosting:bvester-com

echo ""
echo "Step 2: Deployment completed!"
echo ""
echo "Your site is now live at:"
echo "- Staging URL: https://bvester-com.web.app"
echo "- Custom Domain: https://bvester.com (after domain setup)"
echo ""
echo "================================================"
echo "CUSTOM DOMAIN SETUP REQUIRED"
echo "================================================"
echo ""
echo "To connect bvester.com to your Firebase hosting:"
echo ""
echo "1. Go to Firebase Console:"
echo "   https://console.firebase.google.com/project/bizinvest-hub-prod/hosting"
echo ""
echo "2. Click on the 'bvester-com' site"
echo ""
echo "3. Click 'Add custom domain'"
echo ""
echo "4. Enter: bvester.com"
echo ""
echo "5. Follow Firebase's verification steps:"
echo "   - Add TXT record to your DNS"
echo "   - Add A/CNAME records as instructed"
echo ""
echo "6. Wait for domain verification (can take up to 24 hours)"
echo ""
echo "DNS Records you'll likely need to add at your domain registrar:"
echo ""
echo "TXT Record:"
echo "  Name: bvester.com"
echo "  Value: (Firebase will provide this)"
echo ""
echo "A Records:"
echo "  Name: bvester.com"
echo "  Value: 151.101.1.195, 151.101.65.195"
echo ""
echo "CNAME Record (alternative to A records):"
echo "  Name: bvester.com"
echo "  Value: bvester-com.web.app"
echo ""
echo "================================================"

read -p "Press any key to continue..."