name: Deploy Homepage to S3

on:
  push:
    branches: [ main ]
    paths: 
      - 'web-app/index.html'
      - 'web-app/login.html'
      - 'web-app/signup.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
        
    - name: Deploy to S3
      run: |
        echo "Deploying web files to S3..."
        aws s3 cp web-app/index.html s3://bvester-website-public/index.html --content-type "text/html"
        aws s3 cp web-app/login.html s3://bvester-website-public/login.html --content-type "text/html" 
        aws s3 cp web-app/signup.html s3://bvester-website-public/signup.html --content-type "text/html"
        
    - name: Invalidate CloudFront
      run: |
        echo "Invalidating CloudFront cache..."
        aws cloudfront create-invalidation --distribution-id E1234567890123 --paths "/*"
        
    - name: Deployment Complete
      run: |
        echo "✅ Homepage deployment complete!"
        echo "🌐 Check: https://bvester.com"